package com.atelier_nyaarium.switchboard.crypto

import com.atelier_nyaarium.switchboard.proto.Admission
import org.junit.Assert.assertEquals
import org.junit.Assert.assertFalse
import org.junit.Assert.assertTrue
import org.junit.Test

/**
 * Pins the Kotlin admission signing against switchboard's node:crypto. If the
 * canonical encoding or the signature scheme diverges, the node-signed admission
 * below stops verifying here - which would silently break Domain membership.
 */
class AdmissionTest {
	// Generated by node `signAdmission` (src/shared/admission.ts).
	private val ownerSignPub = "Y0xrF5PzLEENPFhCJfwYMdPMOGU3CHlQ9Qb0tnDSnmI="
	private val admission = Admission(
		kind = "gateway",
		signPub = "mRk85hTl4+qIW4mIM9sXNat3+gMC1ZllOsk6QESvMfM=",
		boxPub = "ty2brrXsxRAgR1NBiIfB638IYEqWc0mR15rwjTCL+VI=",
		gatewayId = "laptop",
		issuedAt = 1717171717171L,
		nonce = "bm9uY2U=",
	)
	private val signature = "fyi5V+E3n/8yF62jGy/L2i1J55C39ITuSZO6PARmd+ogNXeOS1DEyLcWgp7vd4dui5PHenAqWpqwTXxxbbgjDQ=="
	private val bytesHex =
		"41444d495353494f4e5f56310a676174657761790a6d526b383568546c342b714957346d494d3973584e6174332b674d43315a6c6c4f736b36514553764d664d3d0a74793262727258737852416752314e4269496642363338495945715763306d52313572776a54434c2b56493d0a6c6170746f700a313731373137313731373137310a626d39755932553d"

	@Test
	fun canonicalBytesMatchNode() {
		val hex = AdmissionCrypto.admissionSigningBytes(admission).joinToString("") { "%02x".format(it) }
		assertEquals(bytesHex, hex)
	}

	@Test
	fun verifiesANodeSignedAdmission() {
		assertTrue(Crypto.verify(AdmissionCrypto.admissionSigningBytes(admission), signature, ownerSignPub))
		// A different owner key must not verify.
		val other = Crypto.generateIdentity()
		assertFalse(Crypto.verify(AdmissionCrypto.admissionSigningBytes(admission), signature, other.sign.pub))
	}

	@Test
	fun signsAndVerifiesLocally() {
		val owner = Crypto.generateIdentity()
		val host = Crypto.generateIdentity()
		val a = Admission("gateway", host.sign.pub, host.box.pub, "desktop", 5000L, "eA==")
		val signed = AdmissionCrypto.signAdmission(a, owner.sign.priv, owner.sign.pub)
		assertTrue(AdmissionCrypto.verifyAdmission(signed, owner.sign.pub))
		assertFalse(AdmissionCrypto.verifyAdmission(signed, host.sign.pub))
	}
}
