package com.atelier_nyaarium.switchboard.crypto

import org.junit.Assert.assertArrayEquals
import org.junit.Assert.assertEquals
import org.junit.Assert.assertFalse
import org.junit.Assert.assertTrue
import org.junit.Test

/**
 * Pins the Kotlin crypto against a vector produced by switchboard's node:crypto
 * (src/shared/crypto.ts). If the two ever diverge on key encoding, HKDF, the
 * cipher, or the signed bytes, the node-sealed envelope below stops opening here.
 */
class CryptoTest {
	// Generated by `bun src/shared/crypto.ts` seal with fixed identities.
	private val senderSignPub = "jmNFFBFuCsqQg5CiQej4HS2/7J9XM00tLnkIx3omfuk="
	private val recipientBoxPub = "3bj61oBasTvgIvCvbMPKjmmKyJdM5lv7oH271HBoS0k="
	private val recipientBoxPriv = "r5fkSnkNtTzanHu5RUbF7uYh390SwLF1zTNk0Kd9m54="
	private val plaintext = "hello federation cross-platform"
	private val env = Crypto.SealedEnvelope(
		ephemeralPub = "w9Y9nLx4yZ0qXhvOj1lzCUbRF7foA0oH2p4k0BPPVEo=",
		nonce = "4bdJL4RtOx+uobLh",
		ciphertext = "hz/EfH4M7PR6mIAYY1I531CLNzP/lbOJ9m33AAiUFZaSfdbAYttBX7c1UDpLnSU=",
		signature = "/L7vL8kvTz3FBZ5Tsui6ncpqJeXr0hyAHUXXOg2ewYzzjbCtWooGtXgFjWKWRvgOxoMBiLefTyrofmBXbr+AAQ==",
	)
	private val sigData = "ADMISSION_V1\nhost\nabc"
	private val sig = "cEMMkWeJ8qDE33TdsG6od9+6OX8XMs2E+ycDTQkNMtNXQtzZRnV6+pMybd0jV8eQtA51wn9LXabwwrzE938tCg=="

	@Test
	fun opensANodeSealedEnvelope() {
		val opened = Crypto.unseal(env, recipientBoxPriv, senderSignPub)
		assertEquals(plaintext, String(opened, Charsets.UTF_8))
	}

	@Test
	fun verifiesANodeSignature() {
		assertTrue(Crypto.verify(sigData.toByteArray(Charsets.UTF_8), sig, senderSignPub))
		assertFalse(Crypto.verify("ADMISSION_V1\nhost\nXXX".toByteArray(Charsets.UTF_8), sig, senderSignPub))
	}

	@Test
	fun fingerprintMatchesNode() {
		assertEquals("A839-E2E1-0D6C-22D9", Crypto.fingerprint(senderSignPub))
	}

	@Test
	fun roundTripsLocally() {
		val sender = Crypto.generateIdentity()
		val recipient = Crypto.generateIdentity()
		val msg = "round trip 🔒".toByteArray(Charsets.UTF_8)
		val sealed = Crypto.seal(msg, recipient.box.pub, sender.sign.priv)
		assertArrayEquals(msg, Crypto.unseal(sealed, recipient.box.priv, sender.sign.pub))
	}

	@Test
	fun rejectsAForgedSenderAndTamper() {
		val sender = Crypto.generateIdentity()
		val attacker = Crypto.generateIdentity()
		val recipient = Crypto.generateIdentity()
		val sealed = Crypto.seal("secret".toByteArray(), recipient.box.pub, attacker.sign.priv)
		// Recipient expects the real sender; attacker signed it.
		try {
			Crypto.unseal(sealed, recipient.box.priv, sender.sign.pub)
			throw AssertionError("expected a bad-signature failure")
		} catch (e: SecurityException) {
			assertTrue(e.message!!.contains("bad signature"))
		}
	}
}
