#!/usr/bin/env bash
#
# No args:   quick-start the primary "switchboard" arbiter (git pull + compose up).
# --setup:   interactive wizard to provision / tear down / clean-re-setup an arbiter
#            instance (for rolling a second Host into the federation).

set -uo pipefail
cd "$(dirname "$0")" || exit 1

INSTANCES_DIR=".instances"

####################
# Helpers

err() { echo "ERROR: $*" >&2; }

# Sanitize an instance id to the same [a-z0-9-] slug the arbiter enforces (host-id.ts).
sanitize_id() {
	local s
	s="$(printf '%s' "$1" | tr '[:upper:]' '[:lower:]' | tr -cs 'a-z0-9-' '-')"
	s="${s#-}"
	s="${s%-}"
	printf '%s' "$s"
}

# The BRIDGE_TOKEN from .env (the legacy primary source), or empty.
env_token() {
	[ -f .env ] && sed -n 's/^BRIDGE_TOKEN=//p' .env | head -1
}

# Is a host TCP port free (not bound by a container or a local listener)?
port_free() {
	local p="$1"
	if docker ps --format '{{.Ports}}' 2>/dev/null | grep -qE "(:|>)${p}->"; then return 1; fi
	if command -v ss >/dev/null 2>&1 && ss -ltnH 2>/dev/null | grep -qE "[:.]${p}[[:space:]]"; then return 1; fi
	return 0
}

next_free_port() {
	local p=20010
	while ! port_free "$p"; do p=$((p + 10)); done
	printf '%s' "$p"
}

# Read a single field out of an instance env file.
env_field() {
	sed -n "s/^$2=//p" "$1" 2>/dev/null | head -1
}

# Compose invocation for an instance (its own project + env-file).
dc() {
	local id="$1"; shift
	docker compose -p "$id" --env-file "$INSTANCES_DIR/$id.env" "$@"
}

wait_health() {
	local port="$1"
	echo "Waiting for the arbiter on :$port ..."
	for _ in $(seq 1 30); do
		if curl -sf "http://localhost:$port/health" >/dev/null 2>&1; then return 0; fi
		sleep 2
	done
	return 1
}

show_qr() {
	local container="$1"
	echo
	echo "=== Admit-host QR (scan with the owner phone, then confirm the SAS below) ==="
	docker logs "$container" 2>&1 | sed -n '/open Enroll by QR/,/Confirm this fingerprint/p' || true
	echo "(empty above = no QR; it only prints when a BRIDGE_TOKEN is set and the Host is un-admitted)"
}

list_ids() {
	local f
	for f in "$INSTANCES_DIR"/*.env; do [ -e "$f" ] && basename "$f" .env; done
}

# Prompt the user to choose a configured instance; echoes the id on stdout.
pick_instance() {
	local ids; mapfile -t ids < <(list_ids)
	if [ "${#ids[@]}" -eq 0 ]; then err "no configured instances under $INSTANCES_DIR/"; return 1; fi
	local i=1 x
	for x in "${ids[@]}"; do echo "  $i) $x" >&2; i=$((i + 1)); done
	local n; read -rp "Pick #: " n
	if ! [[ "$n" =~ ^[0-9]+$ ]] || [ "$n" -lt 1 ] || [ "$n" -gt "${#ids[@]}" ]; then err "invalid choice"; return 1; fi
	printf '%s' "${ids[$((n - 1))]}"
}

####################
# Actions

provision() {
	mkdir -p "$INSTANCES_DIR"

	local id raw
	read -rp "Instance id [switchboard]: " raw
	id="$(sanitize_id "${raw:-switchboard}")"
	[ -n "$id" ] || { err "empty id"; return 1; }
	local envf="$INSTANCES_DIR/$id.env"

	local port volume network container
	if [ "$id" = "switchboard" ]; then
		port=20000; volume="arbiter"; network="switchboard"; container="switchboard"
	else
		port="$(next_free_port)"; volume="arbiter-$id"; container="$id"
		# Avoid a doubled "switchboard-switchboard-2" when the id already carries the prefix.
		case "$id" in switchboard-*) network="$id" ;; *) network="switchboard-$id" ;; esac
	fi
	read -rp "Host port [$port]: " raw; port="${raw:-$port}"

	local deftoken token
	deftoken="$(env_token)"
	if [ -n "$deftoken" ]; then
		read -rp "Bridge token [reuse .env]: " raw; token="${raw:-$deftoken}"
	else
		read -rp "Bridge token (REQUIRED for evie/federation + the admit-host QR): " token
	fi
	[ -n "$token" ] || echo "WARNING: empty token -> the evie bridge will not start (local-only, no QR)."

	local pin
	read -rp "Owner pin FEDERATION_OWNER_SIGN_PUB (optional, Enter to skip): " pin

	echo
	echo "Will create instance '$id':"
	echo "  HOST_ID / hostname : $id"
	echo "  container          : $container"
	echo "  host port          : $port -> 20000 (in-container)"
	echo "  state volume       : ./volumes/$volume"
	echo "  docker network     : $network"
	echo "  bridge token       : ${token:+set}${token:-EMPTY (no evie bridge, no QR)}"
	echo "  owner pin          : ${pin:-none}"
	local go; read -rp "Create + start this? [Y/n]: " go
	case "$go" in n | N) echo "aborted"; return 0 ;; esac

	umask 077
	cat > "$envf" <<EOF
# switchboard arbiter instance "$id" (generated by start-arbiter.sh --setup)
ARBITER_ID=$id
ARBITER_CONTAINER=$container
ARBITER_PORT=$port
ARBITER_VOLUME=$volume
ARBITER_NETWORK=$network
BRIDGE_TOKEN=$token
FEDERATION_OWNER_SIGN_PUB=$pin
EOF
	echo "Wrote $envf"

	echo "Building + starting '$id' ..."
	dc "$id" up --build -d || { err "compose up failed for '$id'"; return 1; }

	if wait_health "$port"; then
		echo "Arbiter '$id' is healthy on :$port (HOST_ID=$id)."
		if [ -n "$token" ]; then sleep 6; show_qr "$container"; fi
	else
		err "'$id' did not become healthy in 60s; check: docker logs $container"
	fi
}

teardown() {
	echo "Tear down which instance?"
	local id; id="$(pick_instance)" || return 0
	local envf="$INSTANCES_DIR/$id.env"

	dc "$id" down --remove-orphans 2>/dev/null || docker rm -f "$id" 2>/dev/null || true
	echo "Stopped '$id'."

	local volume; volume="$(env_field "$envf" ARBITER_VOLUME)"
	if [ -n "$volume" ] && [ -d "volumes/$volume" ]; then
		read -rp "Wipe its state volume volumes/$volume (identity + allowlist)? [y/N]: " w
		[ "$w" = y ] && rm -rf "volumes/${volume:?}" && echo "wiped volumes/$volume"
	fi
	read -rp "Delete its config $envf? [y/N]: " d
	[ "$d" = y ] && rm -f "$envf" && echo "deleted $envf"
}

# Clean re-setup: stop, WIPE the state volume (fresh identity = fresh admit-host QR),
# and restart with the same config. For when an enrollment got into a bad state.
re_setup() {
	echo "Clean re-setup which instance?"
	local id; id="$(pick_instance)" || return 0
	local envf="$INSTANCES_DIR/$id.env"
	[ -f "$envf" ] || { err "no config for '$id'"; return 1; }

	local volume port container
	volume="$(env_field "$envf" ARBITER_VOLUME)"
	port="$(env_field "$envf" ARBITER_PORT)"
	container="$(env_field "$envf" ARBITER_CONTAINER)"
	# A truncated/corrupt config would otherwise wipe nothing and health-check the
	# wrong port, false-reporting failure. Require the fields we are about to act on.
	if [ -z "$volume" ] || [ -z "$port" ] || [ -z "$container" ]; then
		err "config $envf is missing ARBITER_VOLUME/PORT/CONTAINER; re-run option 1 to reprovision"
		return 1
	fi

	echo "This stops '$id', WIPES volumes/$volume (its keypair + allowlist), and restarts it."
	echo "It will re-mint its identity and print a fresh admit-host QR for re-enrollment."
	read -rp "Proceed? [y/N]: " ok; [ "$ok" = y ] || return 0

	dc "$id" down --remove-orphans 2>/dev/null || true
	[ -n "$volume" ] && rm -rf "volumes/${volume:?}"
	dc "$id" up --build -d || { err "compose up failed"; return 1; }

	if wait_health "$port"; then
		echo "'$id' is healthy."
		sleep 6; show_qr "$container"
	else
		err "'$id' did not become healthy; check: docker logs $container"
	fi
}

setup_menu() {
	while true; do
		echo
		echo "switchboard arbiter setup"
		echo "  1) Provision / reconfigure an arbiter"
		echo "  2) Tear down an arbiter"
		echo "  3) Clean re-setup (wipe identity + restart, fresh enrollment)"
		echo "  q) quit"
		local c; read -rp "> " c
		case "$c" in
			1) provision ;;
			2) teardown ;;
			3) re_setup ;;
			q | Q | "") break ;;
			*) echo "?" ;;
		esac
	done
}

####################
# Entry

if [ "${1:-}" = "--setup" ]; then
	setup_menu
	exit 0
fi

# Default: quick-start the primary instance (unchanged behavior).
git fetch --prune || true
git pull || true

docker compose down --remove-orphans 2>/dev/null || true
docker compose up --build -d

echo "Waiting for arbiter to be ready..."
for i in $(seq 1 30); do
	if curl -sf http://localhost:20000/health > /dev/null 2>&1; then
		echo "Arbiter is ready. Waiting 10s for evie-bot connection..."
		sleep 10
		exit 0
	fi
	sleep 2
done

echo "WARNING: Arbiter did not become healthy within 60s"
exit 1
